site_name:  Just Do Security
repo_url:   https://github.com/justdosecurity/justdosecurity.github.io
repo_name:  Just Do Security
site_author:  Just Do Security
site_description: Just Do Security
copyright:  '© 2019 Just Do Security.'

theme:  material
